services:
  app:
    build: .
    container_name: rag_app
    volumes:
      - .:/app
    depends_on:
      - mongo
      - neo4j
    env_file:
      - .env
    command: ["python", "main.py"]  # Hoặc: ["uvicorn", "app:app", "--reload"]

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test12345
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_server_config_strict__validation_enabled=false
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  mongo_data:
  neo4j_data:
  neo4j_logs:
